### ISSUE TITLE
botocore.exceptions.NoRegionError: You must specify a region

### ISSUE THREAD

**Issue by jphe** [dpeerlab/seqc#7]
Hi, 

I have download SEQC, and try to check the help message with "SEQC --help",  but it reports an error like bellow. 

And dose there any detailed tutorial for SEQC that I can follow? 

Thanks, I'm looking forward for your help.

```
SEQC --help
Traceback (most recent call last):
  File "/public/home/jphe/anaconda3/envs/scanpy/bin/SEQC", line 4, in <module>
    __import__('pkg_resources').run_script('seqc==0.2.5', 'SEQC')
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/seqc-0.2.5-py3.6.egg/EGG-INFO/scripts/SEQC", line 4, in <module>
    from seqc.core.main import main
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/seqc-0.2.5-py3.6.egg/seqc/core/__init__.py", line 1, in <module>
    from .progress import progress
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/seqc-0.2.5-py3.6.egg/seqc/core/progress.py", line 2, in <module>
    from seqc import ec2
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/seqc-0.2.5-py3.6.egg/seqc/ec2.py", line 79, in <module>
    class AWSInstance(object):
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/seqc-0.2.5-py3.6.egg/seqc/ec2.py", line 86, in AWSInstance
    ec2 = boto3.resource('ec2')
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/boto3-1.10.42-py3.6.egg/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/boto3-1.10.42-py3.6.egg/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/boto3-1.10.42-py3.6.egg/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/client.py", line 83, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/client.py", line 247, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/args.py", line 153, in compute_client_args
    s3_config=s3_config,
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/args.py", line 217, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/args.py", line 300, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/client.py", line 321, in resolve
    service_name, region_name)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/botocore-1.13.42-py3.6.egg/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
```

**Comment by ambrosejcarr** [comment]
Hi. Thanks for posting this issue. The likely cause of this error is your amazon web services setup. SEQC requires that you pre-run `aws configure` which will populate a configuration file in `~/.aws/config`. 

You can see details in our [readme](https://github.com/dpeerlab/seqc/blob/master/README.md) and on the expectations of boto in [this stackoverflow answer](https://stackoverflow.com/questions/40377662/boto3-client-noregionerror-you-must-specify-a-region-error-only-sometimes). 

Please let us know if you aren't able to get it working.

**Comment by hisplan** [comment]
Thanks, Ambrose.

@jphe if you are trying to run SEQC locally (i.e. without using AWS), you could just do the following to avoid that error:
```
export AWS_DEFAULT_REGION=us-east-1
```

Please reopen this ticket if you still have issues.
